---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  generation: 1
  name: bigbang
  namespace: flux-system
spec:
  gitImplementation: go-git
  interval: 1m0s
  ref:
    tag: 1.56.0
  timeout: 60s
  url: https://repo1.dso.mil/big-bang/bigbang
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: bigbang-values
spec:
  include:
    - repository:
        name: bigbang
      fromPath: chart
      # toPath:  defaults to repository.name https://fluxcd.io/flux/components/source/gitrepositories/#include
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: bigbang
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: bigbang
  path: ./base/
  prune: true
  valuesFrom:
    - kind: Secret
      name: terraform
      optional: true
    - kind: ConfigMap
      name: environment

