---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: bigbang
spec:
  interval: 10m0s
  ref:
    tag: 1.56.0
  timeout: 60s
  url: https://repo1.dso.mil/big-bang/bigbang.git
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: bigbang-values
interval: 1m0s
spec:
  url: https://github.com/Seagard/kubedoom
  ref:
    branch: flux
    include:
    - repository:
        name: bigbang
      fromPath: chart
      toPath: clusters/minikube/bigbang-values/chart
      # toPath:  defaults to repository.name https://fluxcd.io/flux/components/source/gitrepositories/#include
    - repository:
        name: bigbang
      fromPath: base
      toPath: clusters/minikube/bigbang-values/base
